# Generated by Django 6.0.5 on 2026-05-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_recipephoto_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipePhoto',
            new_name='Photo',
        ),
    ]
