# Generated by Django 6.0.5 on 2026-05-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_recipephoto_photo'),
    ]

    operations = [
    ]
