# Generated by Django 6.0.5 on 2026-05-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20260521_2055'),
    ]

    operations = [
    ]
